import { RoleTheme } from "./dashboardTypes";

export const ROLE_THEMES: Record<string, RoleTheme> = {
  fan: {
    accent: "blue",
    text: "text-blue-400",
    bg: "bg-blue-600",
    border: "border-blue-500/20",
    hoverBg: "hover:bg-blue-700",
    lightBg: "bg-blue-950/20",
    shadow: "shadow-blue-600/10",
  },
  volunteer: {
    accent: "green",
    text: "text-green-400",
    bg: "bg-green-600",
    border: "border-green-500/20",
    hoverBg: "hover:bg-green-700",
    lightBg: "bg-green-950/20",
    shadow: "shadow-green-600/10",
  },
  security: {
    accent: "red",
    text: "text-red-400",
    bg: "bg-red-600",
    border: "border-red-500/20",
    hoverBg: "hover:bg-red-700",
    lightBg: "bg-red-950/20",
    shadow: "shadow-red-600/10",
  },
  organizer: {
    accent: "purple",
    text: "text-purple-400",
    bg: "bg-purple-600",
    border: "border-purple-500/20",
    hoverBg: "hover:bg-purple-700",
    lightBg: "bg-purple-950/20",
    shadow: "shadow-purple-600/10",
  },
  venue_staff: {
    accent: "orange",
    text: "text-orange-400",
    bg: "bg-orange-600",
    border: "border-orange-500/20",
    hoverBg: "hover:bg-orange-700",
    lightBg: "bg-orange-950/20",
    shadow: "shadow-orange-600/10",
  },
};

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    liveTicker: "Live Ticker",
    gateInfo: "Gate Info",
    queues: "Queues",
    safety: "Safety",
    emergency: "Emergency",
    settings: "Settings",
    switchRole: "Switch Role",
    roleOnboarding: "Choose Your Role",
    announcements: "Announcements",
    transport: "Transport Status",
    sustainability: "Sustainability Center",
    incidentReport: "Incident Reporting",
    lostFound: "Lost & Found",
    accessibility: "Accessibility",
    aiAssistant: "StadiumOS AI Assistant",
    aiCommandCenter: "AI Operations Command",
    incidentType: "Incident Type",
    location: "Location",
    severity: "Severity",
    description: "Description",
    submit: "Submit",
    clearance: "Cleared",
    quickestConcession: "Quickest Option Nearby",
    waitEst: "Est. Wait",
    walkup: "Walk Up Only",
    savedEvents: "Saved Events",
    itinerary: "Today's Itinerary",
  },
  es: {
    dashboard: "Tablero",
    liveTicker: "Canal en Vivo",
    gateInfo: "Información de Puertas",
    queues: "Colas",
    safety: "Seguridad",
    emergency: "Emergencia",
    settings: "Configuración",
    switchRole: "Cambiar Rol",
    roleOnboarding: "Elige tu Rol",
    announcements: "Anuncios",
    transport: "Estado de Transporte",
    sustainability: "Centro de Sostenibilidad",
    incidentReport: "Reportar Incidente",
    lostFound: "Objetos Perdidos",
    accessibility: "Accesibilidad",
    aiAssistant: "Asistente AI StadiumOS",
    aiCommandCenter: "Comando de Operaciones AI",
    incidentType: "Tipo de Incidente",
    location: "Ubicación",
    severity: "Severidad",
    description: "Descripción",
    submit: "Enviar",
    clearance: "Despejado",
    quickestConcession: "Opción Más Rápida Cercana",
    waitEst: "Espera Est.",
    walkup: "Solo Caminar",
    savedEvents: "Eventos Guardados",
    itinerary: "Itinerario de Hoy",
  },
  fr: {
    dashboard: "Tableau de Bord",
    liveTicker: "Flux en Direct",
    gateInfo: "Infos Portes",
    queues: "Files d'Attente",
    safety: "Sécurité",
    emergency: "Urgence",
    settings: "Paramètres",
    switchRole: "Changer de Rôle",
    roleOnboarding: "Choisissez votre rôle",
    announcements: "Annonces",
    transport: "Statut des Transports",
    sustainability: "Centre de Durabilité",
    incidentReport: "Rapport d'Incident",
    lostFound: "Objets Trouvés",
    accessibility: "Accessibilité",
    aiAssistant: "Assistant IA StadiumOS",
    aiCommandCenter: "Commandement des Opérations IA",
    incidentType: "Type d'Incident",
    location: "Lieu",
    severity: "Gravité",
    description: "Description",
    submit: "Soumettre",
    clearance: "Résolu",
    quickestConcession: "Option la Plus Rapide à Proximité",
    waitEst: "Attente Est.",
    walkup: "Accès Libre",
    savedEvents: "Événements Sauvegardés",
    itinerary: "Itinéraire du Jour",
  },
  ar: {
    dashboard: "لوحة القيادة",
    liveTicker: "البث المباشر",
    gateInfo: "معلومات البوابة",
    queues: "الطوابير",
    safety: "الأمان",
    emergency: "الطوارئ",
    settings: "الإعدادات",
    switchRole: "تغيير الدور",
    roleOnboarding: "اختر دورك",
    announcements: "الإعلانات",
    transport: "حالة النقل",
    sustainability: "مركز الاستدامة",
    incidentReport: "الإبلاغ عن الحوادث",
    lostFound: "المفقودات والمعثورات",
    accessibility: "سهولة الوصول",
    aiAssistant: "مساعد الذكاء الاصطناعي StadiumOS",
    aiCommandCenter: "مركز عمليات الذكاء الاصطناعي",
    incidentType: "نوع الحادث",
    location: "الموقع",
    severity: "الخطورة",
    description: "الوصف",
    submit: "إرسال",
    clearance: "تمت التسوية",
    quickestConcession: "أسرع خيار قريب",
    waitEst: "الانتظار المتوقع",
    walkup: "دخول مباشر فقط",
    savedEvents: "الفعاليات المحفوظة",
    itinerary: "جدول اليوم",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    liveTicker: "लाइव टिकर",
    gateInfo: "गेट जानकारी",
    queues: "कतारें",
    safety: "सुरक्षा",
    emergency: "आपातकालीन",
    settings: "सेटिंग्स",
    switchRole: "भूमिका बदलें",
    roleOnboarding: "अपनी भूमिका चुनें",
    announcements: "घोषणाएँ",
    transport: "परिवहन स्थिति",
    sustainability: "स्थिरता केंद्र",
    incidentReport: "घटना की रिपोर्ट",
    lostFound: "खोया and पाया",
    accessibility: "सुगम्यता",
    aiAssistant: "StadiumOS एआई सहायक",
    aiCommandCenter: "एआई संचालन कमान",
    incidentType: "घटना का प्रकार",
    location: "स्थान",
    severity: "तीव्रता",
    description: "विवरण",
    submit: "जमा करें",
    clearance: "सुलझाया गया",
    quickestConcession: "पास का सबसे तेज़ विकल्प",
    waitEst: "अनुमानित प्रतीक्षा",
    walkup: "केवल वॉक अप",
    savedEvents: "सहेजे गए कार्यक्रम",
    itinerary: "आज की समय-सारिणी",
  },
  ja: {
    dashboard: "ダッシュボード",
    liveTicker: "ライブティッカー",
    gateInfo: "ゲート情報",
    queues: "行列情報",
    safety: "安全対策",
    emergency: "緊急事態",
    settings: "設定",
    switchRole: "ロール切り替え",
    roleOnboarding: "ロールを選択してください",
    announcements: "アナウンス",
    transport: "交通状況",
    sustainability: "サステナビリティセンター",
    incidentReport: "インシデント報告",
    lostFound: "落とし物・忘れ物",
    accessibility: "アクセシビリティ",
    aiAssistant: "StadiumOS AIアシスタント",
    aiCommandCenter: "AI運用指令センター",
    incidentType: "インシデント種別",
    location: "発生場所",
    severity: "深刻度",
    description: "詳細説明",
    submit: "送信",
    clearance: "解決済み",
    quickestConcession: "近隣 of 最速オプション",
    waitEst: "予想待ち時間",
    walkup: "直接並ぶのみ",
    savedEvents: "保存されたイベント",
    itinerary: "本日の日程",
  }
};
